version: '3'

services:
  db:
    container_name: psql
    restart: always
    image: postgres:16
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5435:5435"
    networks:
      - psql-pgql

  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:your_password@db:5435/your_database
      POSTGRAPHILE_CORS: "true"
    command: [
      "--cors",
      "--enhance-graphiql",
      "--allow-explain",
      "--append-plugins", "@graphile-contrib/pg-simplify-inflector",
      "--enable-query-batching",
      "--legacy-relations", "omit",
      "--schema", "public",
      "--host", "0.0.0.0",
      "--port", "8090"
    ]
    ports:
      - "8090:8090"
    networks:
      - psql-pgql

  sveltekit:
    container_name: sveltekit
    build:
      context: .
    ports:
      - "4173:4173"
    networks:
      - psql-pgql
    depends_on:
      - graphql

networks:
  psql-pgql:
    driver: bridge
