version: '3'

services:
  db:
    container_name: psql
    restart: always
    image: postgres:16  # PostgreSQL image
    volumes:
      - ./db/data:/var/lib/postgresql/data  # Data persistence
    environment:
      POSTGRES_USER: postgres               # Hardcoded user
      POSTGRES_PASSWORD: your_password      # Hardcoded password
      POSTGRES_DB: your_database            # Hardcoded database name
    ports:
      - "5432:5432"                         # Expose PostgreSQL port
    networks:
      - psql-pgql

  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile  # GraphQL API
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:your_password@db:5432/your_database
    ports:
      - "5000:5000"                         # Expose GraphQL port
    networks:
      - psql-pgql

networks:
  psql-pgql:
    driver: bridge