version: '3'

services:
  db:
    container_name: psql
    restart: always
    image: postgres:16  # PostgreSQL image
    volumes:
      - ./db/data:/var/lib/postgresql/data  # Veritabanı verilerini saklamak için
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5435:5435"  # PostgreSQL portunu expose eder
    networks:
      - psql-pgql

  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile  # PostGraphile imajı
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:your_password@db:5435/your_database
      POSTGRAPHILE_CORS: "true"  # Enable CORS
    ports:
      - "8090:8090"  # GraphQL API portunu expose eder
    networks:
      - psql-pgql

  sveltekit:
    container_name: sveltekit
    build:
      context: .  # SvelteKit uygulaması bu dizinde
    ports:
      - "4173:4173"  # SvelteKit portu
    networks:
      - psql-pgql
    depends_on:
      - graphql

networks:
  psql-pgql:
    driver: bridge
